version: "3.8"

services:

  vehiclecrud:
    build: .
    ports:
    - 8080:8080
    depends_on:
      - vehiclecrud-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vehiclecrud-db:5432/vehiclecrud
      - SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE=20
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    image: vehiclecrud:dev

  vehiclecrud-db:
    image: postgres:12.3
    container_name: vehiclecrud-db
    hostname: vehiclecrud-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=vehiclecrud
    volumes:
      - vehiclecrud-db-data:/var/lib/postgresql/data

volumes:
  vehiclecrud-db-data: