spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vehiclecrud
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    database: POSTGRESQL
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yml

#swagger settings
springfox:
  documentation:
    swagger:
      v2:
        path: /api